### ISSUE TITLE
bgnet/examples/listener.c only listens to ipv4 on Linux

### ISSUE THREAD

**Issue by MostParsingVex** [beejjorgensen/bgnet#2]
talker.c appears to send udp datagrams over both ipv4 and ipv6 but listener.c appears to only listen on ipv4.

**Comment by beejjorgensen** [comment]
It's coded to listen on whichever it can bind to first.

Try changing this line:

`hints.ai_family = AF_UNSPEC;`

to
`
hints.ai_family = AF_INET6;`

Does that force it?

**Comment by mkrysiak** [comment]
If a reader builds listener.c and talker.c as-is, and executes them, there is a chance the message won't be received by the listener.  In my case, the listener bound to IPv4 first, but the talker sent the message on IPv6.  Since readers most likely have an expectation that all examples work without issue, this can be confusing. So I think it would be good to at least add a note about this behaviour.

**Comment by beejjorgensen** [comment]
Fixed, thanks!
